language: node_js
node_js:
- '0.10'
env:
  matrix:
  - MODULE=pimatic
  - MODULE=pimatic-athome
  - MODULE=pimatic-ble
  - MODULE=pimatic-coc
  - MODULE=pimatic-cron
  - MODULE=pimatic-dht-sensors
  - MODULE=pimatic-dhtxx
  - MODULE=pimatic-ds18b20
  - MODULE=pimatic-edimax
  - MODULE=pimatic-filebrowser
  - MODULE=pimatic-fritz
  - MODULE=pimatic-gpio
  - MODULE=pimatic-homeduino
  - MODULE=pimatic-ifttt
  - MODULE=pimatic-kodi
  - MODULE=pimatic-lcd
  - MODULE=pimatic-links
  - MODULE=pimatic-lm-sensors
  - MODULE=pimatic-location
  - MODULE=pimatic-log-reader
  - MODULE=pimatic-mail
  - MODULE=pimatic-max
  - MODULE=pimatic-mobile-frontend
  - MODULE=pimatic-mochad
  - MODULE=pimatic-mpd
  - MODULE=pimatic-mysensors
  - MODULE=pimatic-nut
  - MODULE=pimatic-openweather
  - MODULE=pimatic-otgw
  - MODULE=pimatic-ouimeaux
  - MODULE=pimatic-piblaster
  - MODULE=pimatic-pilight
  - MODULE=pimatic-ping
  - MODULE=pimatic-play
  - MODULE=pimatic-plugin-iwy-light-master
  - MODULE=pimatic-pushbullet
  - MODULE=pimatic-pushover
  - MODULE=pimatic-sensortag
  - MODULE=pimatic-shell-execute
  - MODULE=pimatic-sispmctl
  - MODULE=pimatic-solarview
  - MODULE=pimatic-sunrise
  - MODULE=pimatic-sysinfo
  - MODULE=pimatic-thinkingcleaner
  - MODULE=pimatic-ultrasonic
  - MODULE=pimatic-voice-recognition
  - MODULE=pimatic-volkszaehler
  - MODULE=pimatic-weather
  - MODULE=pimatic-youless
  - MODULE=pimatic-z-way
  global:
    secure: NYLaVNNjnHMP9bbcuID35LAevUlHXh0ppxHTUZ7yqmIISphYyQtlINlBibPY2ImqdB1b9tg8iOJFr7PKsB8JdQKKPDlquo3hjbE+rO5RhkeYrfbYwi1Kxrr0322MOjVLa0nYGc0EqATzqnjKflHv+BCj/370Y3ZB5fgzfixWu30=
before_install:
- openssl aes-256-cbc -K $encrypted_161a5cc809f6_key -iv $encrypted_161a5cc809f6_iv
  -in deploy_key.enc -out deploy_key -d
- sudo apt-get update -qq
- sudo apt-get -qq install libc6:i386 libncurses5:i386 libstdc++6:i386 zlib1g:i386 curl zlib1g-dev libbluetooth-dev
- npm install -g getversion
install:
- ./setup.sh
script:
- ./build.sh
after_success:
- ./deploy.sh
