language: node_js
node_js:
- '0.10'
env:
  matrix:
  - MODULE=pimatic
  - MODULE=pimatic-anymote
  - MODULE=pimatic-aqara
  - MODULE=pimatic-bluebean
  - MODULE=pimatic-can
  - MODULE=pimatic-chronotherm
  - MODULE=pimatic-dht-sensors
  - MODULE=pimatic-dwd-weather
  - MODULE=pimatic-echo
  - MODULE=pimatic-efergye2
  - MODULE=pimatic-ethboard
  - MODULE=pimatic-filter
  - MODULE=pimatic-foscam
  - MODULE=pimatic-fronius-solar
  - MODULE=pimatic-harmonyhub
  - MODULE=pimatic-homeduino
  - MODULE=pimatic-hue-zll
  - MODULE=pimatic-ifttt
  - MODULE=pimatic-knmi-weather
  - MODULE=pimatic-lgtv
  - MODULE=pimatic-livolo
  - MODULE=pimatic-location
  - MODULE=pimatic-log-to-syslog
  - MODULE=pimatic-mail
  - MODULE=pimatic-maxcul
  - MODULE=pimatic-metar-weather
  - MODULE=pimatic-milight
  - MODULE=pimatic-mopidy
  - MODULE=pimatic-mpower
  - MODULE=pimatic-mysensors
  - MODULE=pimatic-mythermostat
  - MODULE=pimatic-netatmo
  - MODULE=pimatic-nikoniko
  - MODULE=pimatic-nuki
  - MODULE=pimatic-owntracks
  - MODULE=pimatic-ping
  - MODULE=pimatic-play
  - MODULE=pimatic-plugin-openhr20
  - MODULE=pimatic-pushbullet
  - MODULE=pimatic-raspbee
  - MODULE=pimatic-rpi433
  - MODULE=pimatic-smartmeter-gas
  - MODULE=pimatic-sunrise
  - MODULE=pimatic-tplink-smartplug
  - MODULE=pimatic-tts
  - MODULE=pimatic-ultrasonic
  - MODULE=pimatic-unipi-evok
  - MODULE=pimatic-upnp-root
  - MODULE=pimatic-voice-recognition
  - MODULE=pimatic-water-level
  - MODULE=pimatic-websolarlog
  - MODULE=pimatic-wink
  - MODULE=pimatic-wmi
  global:
    secure: NYLaVNNjnHMP9bbcuID35LAevUlHXh0ppxHTUZ7yqmIISphYyQtlINlBibPY2ImqdB1b9tg8iOJFr7PKsB8JdQKKPDlquo3hjbE+rO5RhkeYrfbYwi1Kxrr0322MOjVLa0nYGc0EqATzqnjKflHv+BCj/370Y3ZB5fgzfixWu30=
before_install:
- openssl aes-256-cbc -K $encrypted_161a5cc809f6_key -iv $encrypted_161a5cc809f6_iv
  -in deploy_key.enc -out deploy_key -d
- sudo apt-get update -qq
- sudo apt-get -qq install libc6:i386 libncurses5:i386 libstdc++6:i386 zlib1g:i386 curl zlib1g-dev libbluetooth-dev
- npm install -g getversion
install:
- ./setup.sh
script:
- ./build.sh
after_success:
- ./deploy.sh
