language: node_js
node_js:
  - '0.10'
before_install:
  - openssl aes-256-cbc -K $encrypted_161a5cc809f6_key -iv $encrypted_161a5cc809f6_iv -in deploy_key.enc -out deploy_key -d
  - sudo apt-get update -qq
  - sudo apt-get -qq install libc6:i386 libncurses5:i386 libstdc++6:i386
install:
  - ./setup.sh
script:
  - ./build.sh
after_success:
  - chmod 600 ./deploy_key.pem # this key should have push access
  - ssh-add ./deploy_key.pem
  - ls -al
  - git checkout git@github.com:pimatic-ci/sqlite3.git repo
  - cd repo
  - git push deploy