language: node_js
node_js:
- '0.10'
env:
  matrix:
  - MODULE=pimatic
  - MODULE=pimatic-alarm
  - MODULE=pimatic-alert
  - MODULE=pimatic-assistant
  - MODULE=pimatic-bluelink
  - MODULE=pimatic-broadlink
  - MODULE=pimatic-chromecast
  - MODULE=pimatic-cron
  - MODULE=pimatic-deebot
  - MODULE=pimatic-echo
  - MODULE=pimatic-floorplan
  - MODULE=pimatic-gpio
  - MODULE=pimatic-hap
  - MODULE=pimatic-hass
  - MODULE=pimatic-home-connect
  - MODULE=pimatic-homeduino
  - MODULE=pimatic-i2c
  - MODULE=pimatic-landroid
  - MODULE=pimatic-lg-smart-tv
  - MODULE=pimatic-meross
  - MODULE=pimatic-mqtt-ext
  - MODULE=pimatic-mqtt-publish
  - MODULE=pimatic-nuki-reloaded
  - MODULE=pimatic-phone
  - MODULE=pimatic-ping
  - MODULE=pimatic-probe
  - MODULE=pimatic-raspbee-plus
  - MODULE=pimatic-rfxcom
  - MODULE=pimatic-sabnzbd
  - MODULE=pimatic-save
  - MODULE=pimatic-sma
  - MODULE=pimatic-smartmeter-stats
  - MODULE=pimatic-smartnora
  - MODULE=pimatic-sounds
  - MODULE=pimatic-tado-reloaded
  - MODULE=pimatic-wakeuplight
  - MODULE=pimatic-woox
  global:
    secure: NYLaVNNjnHMP9bbcuID35LAevUlHXh0ppxHTUZ7yqmIISphYyQtlINlBibPY2ImqdB1b9tg8iOJFr7PKsB8JdQKKPDlquo3hjbE+rO5RhkeYrfbYwi1Kxrr0322MOjVLa0nYGc0EqATzqnjKflHv+BCj/370Y3ZB5fgzfixWu30=
before_install:
- openssl aes-256-cbc -K $encrypted_161a5cc809f6_key -iv $encrypted_161a5cc809f6_iv
  -in deploy_key.enc -out deploy_key -d
- sudo apt-get update -qq
- sudo apt-get -qq install libc6:i386 libncurses5:i386 libstdc++6:i386 zlib1g:i386 curl zlib1g-dev libbluetooth-dev
- npm install -g getversion
install:
- ./setup.sh
script:
- ./build.sh
after_success:
- ./deploy.sh
