language: node_js
node_js:
- '0.10'
env:
  matrix:
  - MODULE=pimatic-alarm
  - MODULE=pimatic-alert
  - MODULE=pimatic-amazing-dash-button
  - MODULE=pimatic-angular-material-frontend
  - MODULE=pimatic-anymote
  - MODULE=pimatic-athome
  - MODULE=pimatic-bh1750
  - MODULE=pimatic-ble
  - MODULE=pimatic-bluebean
  - MODULE=pimatic-bmp180
  - MODULE=pimatic-buienradar
  - MODULE=pimatic-calendar
  - MODULE=pimatic-can
  - MODULE=pimatic-chronotherm
  - MODULE=pimatic-coc
  - MODULE=pimatic-cron
  - MODULE=pimatic-customcss
  - MODULE=pimatic-dash-button
  - MODULE=pimatic-denon-avr
  - MODULE=pimatic-dewpoint
  - MODULE=pimatic-dht-sensors
  - MODULE=pimatic-diy-controls
  - MODULE=pimatic-ds18b20
  - MODULE=pimatic-dwd
  - MODULE=pimatic-easybox
  - MODULE=pimatic-echo
  - MODULE=pimatic-edimax
  - MODULE=pimatic-emon
  - MODULE=pimatic-enigma2
  - MODULE=pimatic-ethboard
  - MODULE=pimatic-filebrowser
  - MODULE=pimatic-filter
  - MODULE=pimatic-foscam
  - MODULE=pimatic-fritz
  - MODULE=pimatic-fronius-solar
  - MODULE=pimatic-gpio
  - MODULE=pimatic-hap
  - MODULE=pimatic-harmonyhub
  - MODULE=pimatic-homeduino
  - MODULE=pimatic-homegear
  - MODULE=pimatic-hongkongpollution
  - MODULE=pimatic-hue
  - MODULE=pimatic-hue-zll
  - MODULE=pimatic-iframe
  - MODULE=pimatic-ifttt
  - MODULE=pimatic-intergasincomfort
  - MODULE=pimatic-ipcamera
  - MODULE=pimatic-jeelabs
  - MODULE=pimatic-johnny-five
  - MODULE=pimatic-knmi-weather
  - MODULE=pimatic-kodi
  - MODULE=pimatic-lcd
  - MODULE=pimatic-led-light
  - MODULE=pimatic-links
  - MODULE=pimatic-lirc
  - MODULE=pimatic-lm-sensors
  - MODULE=pimatic-location
  - MODULE=pimatic-log-reader
  - MODULE=pimatic-mail
  - MODULE=pimatic-max
  - MODULE=pimatic-maxcul
  - MODULE=pimatic-metar-weather
  - MODULE=pimatic-milight
  - MODULE=pimatic-milight-reloaded
  - MODULE=pimatic-mjpg
  - MODULE=pimatic-mobile-frontend
  - MODULE=pimatic-mochad
  - MODULE=pimatic-mochad-simple
  - MODULE=pimatic-mopidy
  - MODULE=pimatic-mpd
  - MODULE=pimatic-mpower
  - MODULE=pimatic-mqtt
  - MODULE=pimatic-mqtt-simple
  - MODULE=pimatic-mysensors
  - MODULE=pimatic-mythermostat
  - MODULE=pimatic-netatmo
  - MODULE=pimatic-node-red
  - MODULE=pimatic-nuki
  - MODULE=pimatic-nut
  - MODULE=pimatic-openweather
  - MODULE=pimatic-orvibo
  - MODULE=pimatic-otgw
  - MODULE=pimatic-ouimeaux
  - MODULE=pimatic-owjs
  - MODULE=pimatic-owntracks
  - MODULE=pimatic-phone
  - MODULE=pimatic-piblaster
  - MODULE=pimatic-ping
  - MODULE=pimatic-pio-remote
  - MODULE=pimatic-play
  - MODULE=pimatic-plex
  - MODULE=pimatic-probe
  - MODULE=pimatic-prowl
  - MODULE=pimatic-ps4waker
  - MODULE=pimatic-pushbullet
  - MODULE=pimatic-pushover
  - MODULE=pimatic-pushsafer
  - MODULE=pimatic-quote-of-the-day
  - MODULE=pimatic-rflink
  - MODULE=pimatic-rfxcom
  - MODULE=pimatic-sensibo
  - MODULE=pimatic-sensortag
  - MODULE=pimatic-shell-execute
  - MODULE=pimatic-sispmctl
  - MODULE=pimatic-slack
  - MODULE=pimatic-smartmeter
  - MODULE=pimatic-smartmeter-old
  - MODULE=pimatic-smartmeter2
  - MODULE=pimatic-sms
  - MODULE=pimatic-snmp
  - MODULE=pimatic-solarview
  - MODULE=pimatic-solvisremote
  - MODULE=pimatic-sonos
  - MODULE=pimatic-sunrise
  - MODULE=pimatic-sysinfo
  - MODULE=pimatic-telegram
  - MODULE=pimatic-thinkingcleaner
  - MODULE=pimatic-tplink-smartplug
  - MODULE=pimatic-uber
  - MODULE=pimatic-ultrasonic
  - MODULE=pimatic-unipi-evok
  - MODULE=pimatic-upnp-root
  - MODULE=pimatic-voice-recognition
  - MODULE=pimatic-volkszaehler
  - MODULE=pimatic-vsphere
  - MODULE=pimatic-wakeonlan
  - MODULE=pimatic-watchdog-unix
  - MODULE=pimatic-websolarlog
  - MODULE=pimatic-wemo
  - MODULE=pimatic-wink
  - MODULE=pimatic-wmi
  - MODULE=pimatic-xmpp
  - MODULE=pimatic-yamaha-avr
  - MODULE=pimatic-yoctopuce
  - MODULE=pimatic-youless
  - MODULE=pimatic-z-way
  - MODULE=pimatic-zwave-usb
  global:
    secure: NYLaVNNjnHMP9bbcuID35LAevUlHXh0ppxHTUZ7yqmIISphYyQtlINlBibPY2ImqdB1b9tg8iOJFr7PKsB8JdQKKPDlquo3hjbE+rO5RhkeYrfbYwi1Kxrr0322MOjVLa0nYGc0EqATzqnjKflHv+BCj/370Y3ZB5fgzfixWu30=
before_install:
- openssl aes-256-cbc -K $encrypted_161a5cc809f6_key -iv $encrypted_161a5cc809f6_iv
  -in deploy_key.enc -out deploy_key -d
- sudo apt-get update -qq
- sudo apt-get -qq install libc6:i386 libncurses5:i386 libstdc++6:i386 zlib1g:i386 curl zlib1g-dev libbluetooth-dev
- npm install -g getversion
install:
- ./setup.sh
script:
- ./build.sh
after_success:
- ./deploy.sh
