language: node_js
node_js:
- '0.10'
env:
  matrix:
  - MODULE=pimatic
  - MODULE=pimatic-angular-material-frontend
  - MODULE=pimatic-athome
  - MODULE=pimatic-bh1750
  - MODULE=pimatic-ble
  - MODULE=pimatic-bluebean
  - MODULE=pimatic-calendar
  - MODULE=pimatic-can
  - MODULE=pimatic-coc
  - MODULE=pimatic-cron
  - MODULE=pimatic-denon-avr
  - MODULE=pimatic-dewpoint
  - MODULE=pimatic-dht-sensors
  - MODULE=pimatic-ds18b20
  - MODULE=pimatic-easybox
  - MODULE=pimatic-edimax
  - MODULE=pimatic-emon
  - MODULE=pimatic-enigma2
  - MODULE=pimatic-ethboard
  - MODULE=pimatic-filebrowser
  - MODULE=pimatic-filter
  - MODULE=pimatic-foscam
  - MODULE=pimatic-fritz
  - MODULE=pimatic-fronius-solar
  - MODULE=pimatic-gpio
  - MODULE=pimatic-hap
  - MODULE=pimatic-homeduino
  - MODULE=pimatic-homegear
  - MODULE=pimatic-hue
  - MODULE=pimatic-iframe
  - MODULE=pimatic-ifttt
  - MODULE=pimatic-ipcamera
  - MODULE=pimatic-jeelabs
  - MODULE=pimatic-johnny-five
  - MODULE=pimatic-kodi
  - MODULE=pimatic-lcd
  - MODULE=pimatic-led-light
  - MODULE=pimatic-links
  - MODULE=pimatic-lirc
  - MODULE=pimatic-lm-sensors
  - MODULE=pimatic-location
  - MODULE=pimatic-log-reader
  - MODULE=pimatic-mail
  - MODULE=pimatic-max
  - MODULE=pimatic-maxcul
  - MODULE=pimatic-milight
  - MODULE=pimatic-mobile-frontend
  - MODULE=pimatic-mochad
  - MODULE=pimatic-mpd
  - MODULE=pimatic-mqtt-simple
  - MODULE=pimatic-mysensors
  - MODULE=pimatic-mythermostat
  - MODULE=pimatic-nut
  - MODULE=pimatic-openweather
  - MODULE=pimatic-otgw
  - MODULE=pimatic-ouimeaux
  - MODULE=pimatic-piblaster
  - MODULE=pimatic-ping
  - MODULE=pimatic-pio-remote
  - MODULE=pimatic-play
  - MODULE=pimatic-plex
  - MODULE=pimatic-plugin-ethboard
  - MODULE=pimatic-probe
  - MODULE=pimatic-prowl
  - MODULE=pimatic-pushbullet
  - MODULE=pimatic-pushover
  - MODULE=pimatic-rflink
  - MODULE=pimatic-rfxcom
  - MODULE=pimatic-sensortag
  - MODULE=pimatic-shell-execute
  - MODULE=pimatic-sispmctl
  - MODULE=pimatic-smartmeter
  - MODULE=pimatic-solarview
  - MODULE=pimatic-sonos
  - MODULE=pimatic-sunrise
  - MODULE=pimatic-sysinfo
  - MODULE=pimatic-thinkingcleaner
  - MODULE=pimatic-ultrasonic
  - MODULE=pimatic-unipi-evok
  - MODULE=pimatic-upnp-root
  - MODULE=pimatic-voice-recognition
  - MODULE=pimatic-volkszaehler
  - MODULE=pimatic-wakeonlan
  - MODULE=pimatic-websolarlog
  - MODULE=pimatic-wink
  - MODULE=pimatic-yoctopuce
  - MODULE=pimatic-youless
  - MODULE=pimatic-z-way
  global:
    secure: NYLaVNNjnHMP9bbcuID35LAevUlHXh0ppxHTUZ7yqmIISphYyQtlINlBibPY2ImqdB1b9tg8iOJFr7PKsB8JdQKKPDlquo3hjbE+rO5RhkeYrfbYwi1Kxrr0322MOjVLa0nYGc0EqATzqnjKflHv+BCj/370Y3ZB5fgzfixWu30=
before_install:
- openssl aes-256-cbc -K $encrypted_161a5cc809f6_key -iv $encrypted_161a5cc809f6_iv
  -in deploy_key.enc -out deploy_key -d
- sudo apt-get update -qq
- sudo apt-get -qq install libc6:i386 libncurses5:i386 libstdc++6:i386 zlib1g:i386 curl zlib1g-dev libbluetooth-dev
- npm install -g getversion
install:
- ./setup.sh
script:
- ./build.sh
after_success:
- ./deploy.sh
