language: node_js
node_js:
- '0.10'
env:
  matrix:
  - MODULE=pimatic
  - MODULE=pimatic-alarm
  - MODULE=pimatic-alert
  - MODULE=pimatic-amazing-dash-button
  - MODULE=pimatic-angular-material-frontend
  - MODULE=pimatic-anymote
  - MODULE=pimatic-aqara
  - MODULE=pimatic-assistant
  - MODULE=pimatic-athome
  - MODULE=pimatic-backup
  - MODULE=pimatic-bh1750
  - MODULE=pimatic-ble
  - MODULE=pimatic-ble-itag
  - MODULE=pimatic-ble-mi-flora
  - MODULE=pimatic-ble2
  - MODULE=pimatic-ble2-mi-flora
  - MODULE=pimatic-bluebean
  - MODULE=pimatic-bluelink
  - MODULE=pimatic-bme280
  - MODULE=pimatic-bmp180
  - MODULE=pimatic-bmp280
  - MODULE=pimatic-broadlink
  - MODULE=pimatic-buienradar
  - MODULE=pimatic-calendar
  - MODULE=pimatic-calendar2
  - MODULE=pimatic-can
  - MODULE=pimatic-charts
  - MODULE=pimatic-check-alive
  - MODULE=pimatic-chromecast
  - MODULE=pimatic-chronotherm
  - MODULE=pimatic-chronothermmanu
  - MODULE=pimatic-coc
  - MODULE=pimatic-cron
  - MODULE=pimatic-css-inject
  - MODULE=pimatic-customcss
  - MODULE=pimatic-dash-button
  - MODULE=pimatic-dashboard
  - MODULE=pimatic-datetime
  - MODULE=pimatic-denon-avr
  - MODULE=pimatic-dewpoint
  - MODULE=pimatic-dht-sensors
  - MODULE=pimatic-diy-controls
  - MODULE=pimatic-dlnacasts
  - MODULE=pimatic-dooya
  - MODULE=pimatic-ds18b20
  - MODULE=pimatic-dummies
  - MODULE=pimatic-dwd
  - MODULE=pimatic-dwd-weather
  - MODULE=pimatic-dyson
  - MODULE=pimatic-easybox
  - MODULE=pimatic-echo
  - MODULE=pimatic-edimax
  - MODULE=pimatic-efergye2
  - MODULE=pimatic-emon
  - MODULE=pimatic-enigma2
  - MODULE=pimatic-esp-climate
  - MODULE=pimatic-ethboard
  - MODULE=pimatic-filebrowser
  - MODULE=pimatic-filter
  - MODULE=pimatic-floorplan
  - MODULE=pimatic-foscam
  - MODULE=pimatic-fritz
  - MODULE=pimatic-fronius-solar
  - MODULE=pimatic-gbridge
  - MODULE=pimatic-google-calendar
  - MODULE=pimatic-gpio
  - MODULE=pimatic-hap
  - MODULE=pimatic-harmonyhub
  - MODULE=pimatic-hass
  - MODULE=pimatic-hk-avr
  - MODULE=pimatic-holidays
  - MODULE=pimatic-home-connect
  - MODULE=pimatic-homeduino
  - MODULE=pimatic-homegear
  - MODULE=pimatic-homegear-ws
  - MODULE=pimatic-hongkongpollution
  - MODULE=pimatic-hue
  - MODULE=pimatic-hue-zll
  - MODULE=pimatic-i2c
  - MODULE=pimatic-i2c-bme280
  - MODULE=pimatic-iframe
  - MODULE=pimatic-ifttt
  - MODULE=pimatic-influxdb
  - MODULE=pimatic-intergasincomfort
  - MODULE=pimatic-ipcamera
  - MODULE=pimatic-jeelabs
  - MODULE=pimatic-johnny-five
  - MODULE=pimatic-jointspace
  - MODULE=pimatic-knmi-weather
  - MODULE=pimatic-kodi
  - MODULE=pimatic-landroid
  - MODULE=pimatic-lcd
  - MODULE=pimatic-led-light
  - MODULE=pimatic-lg-smart-tv
  - MODULE=pimatic-lgtv
  - MODULE=pimatic-links
  - MODULE=pimatic-lirc
  - MODULE=pimatic-livolo
  - MODULE=pimatic-lm-sensors
  - MODULE=pimatic-location
  - MODULE=pimatic-log-reader
  - MODULE=pimatic-luftdaten
  - MODULE=pimatic-luxtronik2
  - MODULE=pimatic-mail
  - MODULE=pimatic-max
  - MODULE=pimatic-maxcul
  - MODULE=pimatic-meross
  - MODULE=pimatic-mesh
  - MODULE=pimatic-metar-weather
  - MODULE=pimatic-milight
  - MODULE=pimatic-milight-reloaded
  - MODULE=pimatic-mjpg
  - MODULE=pimatic-mobile-frontend
  - MODULE=pimatic-mochad
  - MODULE=pimatic-mochad-simple
  - MODULE=pimatic-mopidy
  - MODULE=pimatic-mpd
  - MODULE=pimatic-mpower
  - MODULE=pimatic-mqtt
  - MODULE=pimatic-mqtt-ext
  - MODULE=pimatic-mqtt-publish
  - MODULE=pimatic-mqtt-simple
  - MODULE=pimatic-mysensors
  - MODULE=pimatic-mythermostat
  - MODULE=pimatic-nanoleaf
  - MODULE=pimatic-nefit
  - MODULE=pimatic-netatmo
  - MODULE=pimatic-nikoniko
  - MODULE=pimatic-node-red
  - MODULE=pimatic-nuki
  - MODULE=pimatic-nuki-reloaded
  - MODULE=pimatic-nut
  - MODULE=pimatic-nzbget
  - MODULE=pimatic-onkyo-avr
  - MODULE=pimatic-openweather
  - MODULE=pimatic-orvibo
  - MODULE=pimatic-otgw
  - MODULE=pimatic-ouimeaux
  - MODULE=pimatic-owjs
  - MODULE=pimatic-owntracks
  - MODULE=pimatic-phone
  - MODULE=pimatic-piblaster
  - MODULE=pimatic-ping
  - MODULE=pimatic-pio-remote
  - MODULE=pimatic-play
  - MODULE=pimatic-plex
  - MODULE=pimatic-plugin-openhr20
  - MODULE=pimatic-probe
  - MODULE=pimatic-prowl
  - MODULE=pimatic-ps4waker
  - MODULE=pimatic-pushbullet
  - MODULE=pimatic-pushover
  - MODULE=pimatic-pushsafer
  - MODULE=pimatic-quote-of-the-day
  - MODULE=pimatic-raspbee
  - MODULE=pimatic-raspbee-plus
  - MODULE=pimatic-rfl868
  - MODULE=pimatic-rflink
  - MODULE=pimatic-rfxcom
  - MODULE=pimatic-rpi433
  - MODULE=pimatic-rtl433
  - MODULE=pimatic-sabnzbd
  - MODULE=pimatic-samsung-tv
  - MODULE=pimatic-samsung-tv-2016
  - MODULE=pimatic-save
  - MODULE=pimatic-sensibo
  - MODULE=pimatic-sensortag
  - MODULE=pimatic-serial
  - MODULE=pimatic-serial-benqbeamer
  - MODULE=pimatic-serial-ivisions
  - MODULE=pimatic-shell-execute
  - MODULE=pimatic-sispmctl
  - MODULE=pimatic-slack
  - MODULE=pimatic-slide
  - MODULE=pimatic-sma
  - MODULE=pimatic-smartmeter
  - MODULE=pimatic-smartmeter-gas
  - MODULE=pimatic-smartmeter-obis
  - MODULE=pimatic-smartmeter-old
  - MODULE=pimatic-smartmeter-stats
  - MODULE=pimatic-smartmeter2
  - MODULE=pimatic-smartmeter3
  - MODULE=pimatic-smartnora
  - MODULE=pimatic-sms
  - MODULE=pimatic-snmp
  - MODULE=pimatic-solarview
  - MODULE=pimatic-solvisremote
  - MODULE=pimatic-sonos
  - MODULE=pimatic-sounds
  - MODULE=pimatic-sounds-basic
  - MODULE=pimatic-spotify
  - MODULE=pimatic-stats
  - MODULE=pimatic-sunrise
  - MODULE=pimatic-switchbot
  - MODULE=pimatic-sysinfo
  - MODULE=pimatic-tado-reloaded
  - MODULE=pimatic-tankerkoenig
  - MODULE=pimatic-telegram
  - MODULE=pimatic-thinkingcleaner
  - MODULE=pimatic-tools
  - MODULE=pimatic-tplink-smartplug
  - MODULE=pimatic-tradfri
  - MODULE=pimatic-tts
  - MODULE=pimatic-tuya
  - MODULE=pimatic-tv-program
  - MODULE=pimatic-uber
  - MODULE=pimatic-ultrasonic
  - MODULE=pimatic-unieq-box
  - MODULE=pimatic-unipi-evok
  - MODULE=pimatic-upnp-root
  - MODULE=pimatic-voice-recognition
  - MODULE=pimatic-volkszaehler
  - MODULE=pimatic-vr-harmonyhub
  - MODULE=pimatic-vsphere
  - MODULE=pimatic-vvo
  - MODULE=pimatic-wago
  - MODULE=pimatic-wakeonlan
  - MODULE=pimatic-wakeuplight
  - MODULE=pimatic-watchdog-unix
  - MODULE=pimatic-water-level
  - MODULE=pimatic-wavtrigger
  - MODULE=pimatic-websolarlog
  - MODULE=pimatic-wemo
  - MODULE=pimatic-wifiswitch
  - MODULE=pimatic-wink
  - MODULE=pimatic-wmi
  - MODULE=pimatic-woox
  - MODULE=pimatic-wunderground
  - MODULE=pimatic-xbox
  - MODULE=pimatic-xmpp
  - MODULE=pimatic-yamaha-avr
  - MODULE=pimatic-yoctopuce
  - MODULE=pimatic-youless
  - MODULE=pimatic-z-way
  - MODULE=pimatic-ziggo-mediabox
  - MODULE=pimatic-zwave-usb
  global:
    secure: NYLaVNNjnHMP9bbcuID35LAevUlHXh0ppxHTUZ7yqmIISphYyQtlINlBibPY2ImqdB1b9tg8iOJFr7PKsB8JdQKKPDlquo3hjbE+rO5RhkeYrfbYwi1Kxrr0322MOjVLa0nYGc0EqATzqnjKflHv+BCj/370Y3ZB5fgzfixWu30=
before_install:
- openssl aes-256-cbc -K $encrypted_161a5cc809f6_key -iv $encrypted_161a5cc809f6_iv
  -in deploy_key.enc -out deploy_key -d
- sudo apt-get update -qq
- sudo apt-get -qq install libc6:i386 libncurses5:i386 libstdc++6:i386 zlib1g:i386 curl zlib1g-dev libbluetooth-dev
- npm install -g getversion
install:
- ./setup.sh
script:
- ./build.sh
after_success:
- ./deploy.sh
